

##  actuator配置
management:
  endpoints:
    web:
      exposure:
        # 显式配置不需要权限验证对外开放的端点
        include: "*"
      # Actuator 的 Web 访问方式的根地址为 /actuator，可以通过 management.endpoints.web.base-path 参数进行修改
#      base-path: /monitor
    # 禁用所有执行器端点
#    enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
#    info:
#      enabled: true
    metrics:
      enabled: true
      sensitive: false
  # JVM (Micrometer)要求给应用设置commonTag
  metrics:
    tags:
      application:  ${spring.application.name}
    export:
      prometheus:
        enabled:  true
# JSON 打印输出
spring:
  jackson:
    serialization:
      indent_output: true
  #去掉重复的metrics
  metrics:
    servo:
      enabled: false


# feign 配置
feign:
  hystrix:
    enabled: true #开启hystrix
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false
#  client:
#    config:
#      #      feignName:
#      default:
#        connectTimeout: 100000
#        readTimeout: 100000
#      tplhk-print:
#        connectTimeout: 60000
#        readTimeout: 60000
#      tplhk-content:
#        connectTimeout: 100000
#        readTimeout: 100000

#配置hystrix超时
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #断路器超时时间，默认1000ms
          strategy: SEMAPHORE


# 更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
eureka:
  instance:
    prefer-ip-address: false #使用服务的id地址注册
    lease-expiration-duration-in-seconds: 90  # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔（默认30秒）
  client:
    healthcheck:
      enabled:  true    # 开启健康检查（需要spring-boot-starter-actuator依赖）
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    serviceUrl: #注册中心的注册地址
#      defaultZone: http://admin:admin@localhost:8761/eureka/      